#!/bin/sh
. /var/log/installer/autopilot
export DBUS_SESSION_BUS_ADDRESS
export LINGMO-INSTALLER_PID

# Disable X access control to let root access :0
xhost +
#launch vis using autopilot py2
sudo -E autopilot vis
