#! /bin/sh
set -e

. /usr/share/debconf/confmodule

/usr/lib/lingmo-installer/netcfg/netcfg

if [ -f /usr/lib/network-manager/ifblacklist_migrate.sh ]; then
	NETCFG=1 /usr/lib/network-manager/ifblacklist_migrate.sh
fi
