#!/bin/sh
# startup logic of lingmo-installer-dm, shared between upstart job and systemd unit

set -e
test -x /usr/bin/lingmo-installer-dm || exit 0

lingmo-installer=
automatic=
debug=
ldtp=
noninteractive=
choose=
frontend=
for x in $(cat /proc/cmdline); do
    case $x in
	debug-lingmo-installer)
	    debug="-d"
	    lingmo-installer=1
	    ;;
	automatic-lingmo-installer)
	    automatic="--automatic"
	    lingmo-installer=1
	    ;;
	maybe-lingmo-installer)
	    lingmo-installer=1
	    choose="--greeter"
	    ;;
	ldtp-lingmo-installer)
	    lingmo-installer=1
	    ldtp="--ldtp"
	    ;;
	only-lingmo-installer)
	    lingmo-installer=1
	    ;;
	noninteractive)
	    lingmo-installer=1
	    noninteractive=1
	    ;;
	lingmo-installer/frontend=*)
	    frontend="${x#*=}"
	    ;;
    esac
done
[ "$lingmo-installer" ] || exit 0

if [ -r /etc/default/locale ]; then
    . /etc/default/locale
    if [ -n "$LANG" ]; then
	export LANG
    fi
    if [ -n "$LANGUAGE" ]; then
	export LANGUAGE
    fi
fi

[ -e /run/systemd/system ] || initctl emit starting-dm DM=lingmo-installer-dm

# turn off console blanking for install process
setterm -blank 0 -term linux > /dev/console || true

if [ -n "$noninteractive" ]; then
    plymouth quit || :
    exec lingmo-installer noninteractive $debug
else
    if ! lingmo-installer-dm vt1 :0 lingmo /usr/bin/lingmo-installer $debug $automatic $choose $ldtp --only $frontend; then
	# has X crashed, or has lingmo-installer?
	if [ "$automatic" ] && ! [ -f /var/log/installer/version ]; then
	    # in case we crashed before the X startup sequence
	    plymouth quit || :
	    exec lingmo-installer noninteractive $debug
	else
	    # something more serious has happened, e.g. debconf locked?!
	    exit 1
	fi
    fi
fi
exit 0
